// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Demo
{
    [DemoResourceType("demo:index:Demo")]
    public partial class Demo : Pulumi.ComponentResource
    {
        /// <summary>
        /// Create a Demo resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Demo(string name, DemoArgs args, ComponentResourceOptions? options = null)
            : base("demo:index:Demo", name, args ?? new DemoArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class DemoArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The static page.
        /// </summary>
        [Input("staticPage", required: true)]
        public Input<Pulumi.Demo.StaticPage> StaticPage { get; set; } = null!;

        public DemoArgs()
        {
        }
    }
}
