// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import {StaticPage} from "./index";

export class Demo extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'demo:index:Demo';

    /**
     * Returns true if the given object is an instance of Demo.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Demo {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Demo.__pulumiType;
    }


    /**
     * Create a Demo resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DemoArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.staticPage === undefined) && !opts.urn) {
                throw new Error("Missing required property 'staticPage'");
            }
            resourceInputs["staticPage"] = args ? args.staticPage : undefined;
        } else {
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Demo.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Demo resource.
 */
export interface DemoArgs {
    /**
     * The static page.
     */
    staticPage: pulumi.Input<StaticPage>;
}
